### ISSUE TITLE
Json schema to support IDE integration

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry-incubator/multiapps#111]
### Description

MTA does not seem to have IDE support yet. IDE now support JSON schema to Yaml documents (e.g. in [intellij](https://www.jetbrains.com/help/idea/json.html)), which automatically selects and downloads the associated Json schema based on registered file patterns (in our case `./manifest.yml`) in http://schemastore.org/json/, and then provides completion as well as inline documentation/hints. 

See related support request in CF app manifest support at https://github.com/cloudfoundry/cloud_controller_ng/issues/1331

This might complement existing YML schema at https://github.com/cloudfoundry-incubator/multiapps/blob/master/spec/schemas/v3/v3.1/mta-schema.yaml

**Comment by nvvalchev** [comment]
Nice idea and thanks for suggesting that! We'd add it to our backlog. Indeed the work needed to support the schema validation doesn't seem that much. As a next step we are already planning to develop a language server protocol based extension for most popular IDEs that might provide even more comprehensive modelling support, but anyway the schema validation approach would be a great quick win.

**Comment by VaskoBozhurski** [comment]
We've added the schemas for version 3.3 of the MTA spec:
http://json.schemastore.org/mtad
http://json.schemastore.org/mtaext
