### ISSUE TITLE
Deploying with 'zdm-mode: true' cannot get required dependencies

### ISSUE THREAD

**Issue by ebusho** [cloudfoundry-incubator/multiapps#93]
I tried to deploy my app using `zdm-mode`, and at the beginning of deployment it gives me the following error:

`ERR    Unexpected error: while trying to invoke the method java.util.List.iterator() of a null object returned from com.sap.cloud.lm.sl.mta.model.v3_1.Resource.getRequiredDependencies()`

Deploying it with `xs bg-deploy` command, without specifying `zdm-mode` in the descriptor file works without issues.

I'm using the (currently)latest SAP HANA, express edition version : 2.00.033.00.20180925.2

_mta.yaml_ file:
https://gist.github.com/ebusho/4abcd71858179a09aa3b820b636ae508

_MAIN_LOG_ file:
https://gist.github.com/ebusho/758ea796dea506d7fbf726e046db0fa3

P.S. I've hidden few parts in the _MAIN_LOG_ file (hostname, username, org...) with `<***>`.

**Comment by nictas** [comment]
Hi @ebusho,

First of all, apologies for the late response! `zdm-mode`, however, is an SAP XSA specific parameter is therefore not supported through our open-source project. Please open an SAP customer incident and we'll take a look at the issue there.
